import { Injectable, Logger, OnModuleDestroy } from '@nestjs/common';
import puppeteer, { Browser } from 'puppeteer';
import { getPuppeteerLaunchOptions } from '../common/puppeteer.config';
import { format } from 'date-fns';
import type { PlReportResult } from './reports.service';

interface AgeingReportData {
  asOf: string;
  totalOutstanding: number;
  buckets: Record<
    string,
    { count: number; total: number; invoices: { invoiceNumber: string; clientId: string; remaining: number; dueDate: Date | string }[] }
  >;
}

interface ExpenseReportData {
  month: string;
  totalAmount: number;
  previousMonthTotal: number;
  momChangePercent: number;
  byCategory: { category: string; amount: number; previousAmount: number; changePercent: number }[];
  expenses: { date: string | Date; vendorName: string; category: string; amount: number }[];
}

@Injectable()
export class ReportPdfService implements OnModuleDestroy {
  private readonly logger = new Logger(ReportPdfService.name);
  private browserPromise: Promise<Browser> | null = null;

  async onModuleDestroy(): Promise<void> {
    if (this.browserPromise) {
      const browser = await this.browserPromise;
      await browser.close();
      this.browserPromise = null;
    }
  }

  private async getBrowser(): Promise<Browser> {
    if (!this.browserPromise) {
      this.browserPromise = puppeteer.launch(getPuppeteerLaunchOptions());
    }
    return this.browserPromise;
  }

  private async renderPdf(html: string): Promise<Buffer> {
    const browser = await this.getBrowser();
    const page = await browser.newPage();
    try {
      await page.setContent(html, { waitUntil: 'domcontentloaded' });
      const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '40px', bottom: '40px', left: '40px', right: '40px' },
      });
      return Buffer.from(pdf);
    } finally {
      await page.close();
    }
  }

  private fmt(n: number): string {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'RWF',
    }).format(n);
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  private footer(): string {
    const ts = new Date().toLocaleString('en-US');
    return `<div style="margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:11px;color:#64748b;text-align:center;">
      Generated by CDY In-House System &bull; ${ts} &bull; Confidential
    </div>`;
  }

  private header(title: string, subtitle: string): string {
    return `<div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;">
      <div>
        <h1 style="margin:0;font-size:22px;color:#C41E3A;letter-spacing:1px;">${this.escapeHtml(title)}</h1>
        <p style="margin:8px 0 0;color:#475569;font-size:13px;">${this.escapeHtml(subtitle)}</p>
      </div>
      <div style="text-align:right;">
        <div style="font-size:20px;font-weight:bold;color:#C41E3A;">CDY</div>
        <div style="font-size:11px;color:#64748b;">In-House System</div>
      </div>
    </div>`;
  }

  async generatePLReport(data: PlReportResult): Promise<Buffer> {
    const from = format(new Date(data.period.from), 'MMMM d, yyyy');
    const to = format(new Date(data.period.to), 'MMMM d, yyyy');
    const prev = data.previousPeriod;

    const revenueRows = data.revenue.byServiceType
      .map(
        (r) => `<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${this.escapeHtml(r.serviceType)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(r.amount)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;color:#64748b;">${this.fmt(prev.revenueByServiceType.find((p) => p.serviceType === r.serviceType)?.amount ?? 0)}</td>
        </tr>`,
      )
      .join('');

    const cogsRows = data.costOfServices.byCategory
      .map(
        (r) => `<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${r.category}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(r.amount)}</td>
        </tr>`,
      )
      .join('');

    const opexRows = data.operatingExpenses.byCategory
      .map(
        (r) => `<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${r.category}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(r.amount)}</td>
        </tr>`,
      )
      .join('');

    const netColor = data.netProfit >= 0 ? '#16a34a' : '#C41E3A';

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
    <body style="font-family:Arial,sans-serif;color:#0f172a;background:#fff;padding:0;margin:0;">
      ${this.header('PROFIT & LOSS REPORT', `${from} — ${to}`)}
      <h2 style="font-size:12px;color:#C41E3A;letter-spacing:2px;margin:24px 0 8px;">REVENUE</h2>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <thead><tr style="background:#f8fafc;">
          <th style="padding:8px 12px;text-align:left;">Service Type</th>
          <th style="padding:8px 12px;text-align:right;">Current</th>
          <th style="padding:8px 12px;text-align:right;">Previous</th>
        </tr></thead>
        <tbody>${revenueRows}</tbody>
        <tfoot><tr style="font-weight:bold;background:#f0fdf4;">
          <td style="padding:10px 12px;">TOTAL REVENUE</td>
          <td style="padding:10px 12px;text-align:right;color:#16a34a;">${this.fmt(data.revenue.total)}</td>
          <td style="padding:10px 12px;text-align:right;">${this.fmt(prev.totalRevenue)}</td>
        </tr></tfoot>
      </table>
      <h2 style="font-size:12px;color:#C41E3A;letter-spacing:2px;margin:24px 0 8px;">COST OF SERVICES</h2>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <tbody>${cogsRows}</tbody>
        <tfoot><tr style="font-weight:bold;"><td style="padding:10px 12px;">TOTAL COGS</td><td style="padding:10px 12px;text-align:right;">${this.fmt(data.costOfServices.total)}</td></tr></tfoot>
      </table>
      <div style="margin:16px 0;padding:12px 16px;background:#fef2f2;border-left:4px solid #C41E3A;">
        <strong>GROSS PROFIT:</strong> ${this.fmt(data.grossProfit)} &nbsp;|&nbsp; Margin: ${data.grossMargin}%
      </div>
      <h2 style="font-size:12px;color:#C41E3A;letter-spacing:2px;margin:24px 0 8px;">OPERATING EXPENSES</h2>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <tbody>${opexRows}</tbody>
        <tfoot><tr style="font-weight:bold;"><td style="padding:10px 12px;">TOTAL OPEX</td><td style="padding:10px 12px;text-align:right;">${this.fmt(data.operatingExpenses.total)}</td></tr></tfoot>
      </table>
      <div style="margin:16px 0;padding:16px;background:#f8fafc;border:2px solid ${netColor};">
        <div style="font-size:18px;font-weight:bold;color:${netColor};">NET PROFIT: ${this.fmt(data.netProfit)}</div>
        <div style="margin-top:4px;color:#475569;">Net Margin: ${data.netMargin}%</div>
      </div>
      ${this.footer()}
    </body></html>`;

    this.logger.debug('Generated P&L PDF');
    return this.renderPdf(html);
  }

  async generateAgeingReport(data: AgeingReportData): Promise<Buffer> {
    const asOf = format(new Date(data.asOf), 'MMMM d, yyyy');
    const bucketLabels: Record<string, { label: string; color: string }> = {
      current: { label: 'Current', color: '#64748b' },
      days1_30: { label: '1–30 Days Overdue', color: '#ca8a04' },
      days31_60: { label: '31–60 Days Overdue', color: '#ea580c' },
      days61_90: { label: '61–90 Days Overdue', color: '#dc2626' },
      days90plus: { label: '90+ Days Overdue', color: '#C41E3A' },
    };

    let sections = '';
    for (const [key, bucket] of Object.entries(data.buckets)) {
      const meta = bucketLabels[key] ?? { label: key, color: '#64748b' };
      const rows = bucket.invoices
        .map(
          (inv) => `<tr>
            <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;font-family:monospace;">${this.escapeHtml(inv.invoiceNumber)}</td>
            <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">${this.escapeHtml(inv.clientId)}</td>
            <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(inv.remaining)}</td>
            <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">${format(new Date(inv.dueDate), 'MMM d, yyyy')}</td>
          </tr>`,
        )
        .join('');

      sections += `<div style="margin-bottom:20px;border:1px solid ${meta.color}33;border-radius:8px;padding:12px;">
        <div style="color:${meta.color};font-weight:bold;margin-bottom:8px;">${meta.label} — ${bucket.count} invoices — ${this.fmt(bucket.total)}</div>
        ${bucket.count > 0 ? `<table style="width:100%;border-collapse:collapse;font-size:12px;">
          <thead><tr style="background:#f8fafc;">
            <th style="padding:6px 10px;text-align:left;">Invoice #</th>
            <th style="padding:6px 10px;text-align:left;">Client</th>
            <th style="padding:6px 10px;text-align:right;">Remaining</th>
            <th style="padding:6px 10px;text-align:left;">Due Date</th>
          </tr></thead><tbody>${rows}</tbody></table>` : '<p style="color:#94a3b8;font-size:12px;">No invoices</p>'}
      </div>`;
    }

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
    <body style="font-family:Arial,sans-serif;color:#0f172a;background:#fff;">
      ${this.header('INVOICE AGEING REPORT', `As of ${asOf}`)}
      <div style="font-size:24px;font-weight:bold;margin:16px 0;color:#0f172a;">
        Total Outstanding: ${this.fmt(data.totalOutstanding)}
      </div>
      ${sections}
      ${this.footer()}
    </body></html>`;

    this.logger.debug('Generated ageing PDF');
    return this.renderPdf(html);
  }

  async generateExpenseReport(data: ExpenseReportData): Promise<Buffer> {
    const maxAmount = Math.max(...data.byCategory.map((c) => c.amount), 1);

    const bars = data.byCategory
      .map((c) => {
        const pct = ((c.amount / data.totalAmount) * 100).toFixed(1);
        const width = ((c.amount / maxAmount) * 100).toFixed(1);
        return `<div style="margin-bottom:12px;">
          <div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:4px;">
            <span>${c.category}</span>
            <span>${this.fmt(c.amount)} (${pct}%)</span>
          </div>
          <div style="background:#0A1628;height:20px;border-radius:4px;overflow:hidden;">
            <div style="background:#C41E3A;height:100%;width:${width}%;"></div>
          </div>
        </div>`;
      })
      .join('');

    const categoryTable = data.byCategory
      .map(
        (c) => `<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${c.category}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(c.amount)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(c.previousAmount)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${c.changePercent > 0 ? '+' : ''}${c.changePercent}%</td>
        </tr>`,
      )
      .join('');

    const expenseRows = data.expenses
      .map(
        (e) => `<tr>
          <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">${format(new Date(e.date), 'MMM d, yyyy')}</td>
          <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">${this.escapeHtml(e.vendorName)}</td>
          <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">${e.category}</td>
          <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(e.amount)}</td>
        </tr>`,
      )
      .join('');

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
    <body style="font-family:Arial,sans-serif;color:#0f172a;background:#fff;">
      ${this.header('EXPENSE SUMMARY', data.month)}
      <div style="margin:16px 0;font-size:14px;">
        Total: <strong>${this.fmt(data.totalAmount)}</strong> &nbsp;|&nbsp;
        Previous: ${this.fmt(data.previousMonthTotal)} &nbsp;|&nbsp;
        Change: ${data.momChangePercent > 0 ? '+' : ''}${data.momChangePercent}%
      </div>
      <h2 style="font-size:12px;color:#C41E3A;letter-spacing:2px;">BY CATEGORY</h2>
      ${bars}
      <table style="width:100%;border-collapse:collapse;font-size:13px;margin-top:24px;">
        <thead><tr style="background:#f8fafc;">
          <th style="padding:8px 12px;text-align:left;">Category</th>
          <th style="padding:8px 12px;text-align:right;">This Month</th>
          <th style="padding:8px 12px;text-align:right;">Last Month</th>
          <th style="padding:8px 12px;text-align:right;">Change</th>
        </tr></thead>
        <tbody>${categoryTable}</tbody>
      </table>
      <h2 style="font-size:12px;color:#C41E3A;letter-spacing:2px;margin-top:24px;">EXPENSE DETAIL</h2>
      <table style="width:100%;border-collapse:collapse;font-size:12px;">
        <thead><tr style="background:#f8fafc;">
          <th style="padding:6px 10px;text-align:left;">Date</th>
          <th style="padding:6px 10px;text-align:left;">Vendor</th>
          <th style="padding:6px 10px;text-align:left;">Category</th>
          <th style="padding:6px 10px;text-align:right;">Amount</th>
        </tr></thead>
        <tbody>${expenseRows}</tbody>
      </table>
      ${this.footer()}
    </body></html>`;

    this.logger.debug('Generated expense PDF');
    return this.renderPdf(html);
  }

  async generateCashFlowReport(data: {
    openingBalance: number;
    forecastPeriod: { from: string; to: string; weeks: number };
    totalExpectedInflows: number;
    totalExpectedOutflows: number;
    lowestProjectedBalance: number;
    hasShortfall: boolean;
    shortfallWeeks: string[];
    weeks: {
      weekLabel: string;
      inflows: number;
      outflows: number;
      netFlow: number;
      runningBalance: number;
      isNegative: boolean;
    }[];
  }): Promise<Buffer> {
    const rows = data.weeks
      .map(
        (w) => `<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${this.escapeHtml(w.weekLabel)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(w.inflows)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(w.outflows)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(w.netFlow)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;text-align:right;color:${w.isNegative ? '#C41E3A' : '#0f172a'};">${this.fmt(w.runningBalance)}</td>
        </tr>`,
      )
      .join('');

    const shortfallNote = data.hasShortfall
      ? `<div style="margin:16px 0;padding:12px 16px;background:#fef2f2;border-left:4px solid #C41E3A;color:#C41E3A;">
          Projected shortfall in: ${data.shortfallWeeks.map((w) => this.escapeHtml(w)).join(', ')}
        </div>`
      : '';

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
    <body style="font-family:Arial,sans-serif;color:#0f172a;background:#fff;">
      ${this.header('CASH FLOW FORECAST', `${data.forecastPeriod.weeks}-week projection`)}
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:20px;font-size:13px;">
        <div>Opening Balance: <strong>${this.fmt(data.openingBalance)}</strong></div>
        <div>Expected Inflows: <strong>${this.fmt(data.totalExpectedInflows)}</strong></div>
        <div>Expected Outflows: <strong>${this.fmt(data.totalExpectedOutflows)}</strong></div>
        <div>Lowest Balance: <strong style="color:${data.lowestProjectedBalance < 0 ? '#C41E3A' : '#0f172a'};">${this.fmt(data.lowestProjectedBalance)}</strong></div>
      </div>
      ${shortfallNote}
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <thead><tr style="background:#f8fafc;">
          <th style="padding:8px 12px;text-align:left;">Week</th>
          <th style="padding:8px 12px;text-align:right;">Inflows</th>
          <th style="padding:8px 12px;text-align:right;">Outflows</th>
          <th style="padding:8px 12px;text-align:right;">Net</th>
          <th style="padding:8px 12px;text-align:right;">Balance</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
      ${this.footer()}
    </body></html>`;

    this.logger.debug('Generated cash flow PDF');
    return this.renderPdf(html);
  }

  async generateBalanceSheetReport(data: {
    asOf: string;
    assets: {
      accountsReceivable: number;
      manual: { label: string; amount: number }[];
      totalAssets: number;
    };
    liabilities: {
      accountsPayable: number;
      manual: { label: string; amount: number }[];
      totalLiabilities: number;
    };
    equity: number;
  }): Promise<Buffer> {
    const asOf = format(new Date(data.asOf), 'MMMM d, yyyy');
    const equityColor = data.equity >= 0 ? '#16a34a' : '#C41E3A';

    const assetManualRows = data.assets.manual
      .map(
        (e) =>
          `<tr><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">${e.label}</td><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(e.amount)}</td></tr>`,
      )
      .join('');

    const liabilityManualRows = data.liabilities.manual
      .map(
        (e) =>
          `<tr><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">${e.label}</td><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(e.amount)}</td></tr>`,
      )
      .join('');

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
    <body style="font-family:Arial,sans-serif;color:#0f172a;background:#fff;">
      ${this.header('BALANCE SHEET', `As of ${asOf}`)}
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-top:24px;">
        <div>
          <h2 style="font-size:12px;color:#C41E3A;letter-spacing:2px;margin-bottom:12px;">ASSETS</h2>
          <table style="width:100%;border-collapse:collapse;font-size:13px;">
            <tr><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">Accounts Receivable</td><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(data.assets.accountsReceivable)}</td></tr>
            ${assetManualRows}
            <tr style="font-weight:bold;"><td style="padding:10px 0;">TOTAL ASSETS</td><td style="padding:10px 0;text-align:right;">${this.fmt(data.assets.totalAssets)}</td></tr>
          </table>
        </div>
        <div>
          <h2 style="font-size:12px;color:#C41E3A;letter-spacing:2px;margin-bottom:12px;">LIABILITIES</h2>
          <table style="width:100%;border-collapse:collapse;font-size:13px;">
            <tr><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">Accounts Payable</td><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;text-align:right;">${this.fmt(data.liabilities.accountsPayable)}</td></tr>
            ${liabilityManualRows}
            <tr style="font-weight:bold;"><td style="padding:10px 0;">TOTAL LIABILITIES</td><td style="padding:10px 0;text-align:right;">${this.fmt(data.liabilities.totalLiabilities)}</td></tr>
          </table>
        </div>
      </div>
      <div style="margin-top:32px;padding:16px;background:#0A1628;border-radius:8px;text-align:center;">
        <div style="font-size:12px;color:#94a3b8;letter-spacing:1px;">NET EQUITY (Assets − Liabilities)</div>
        <div style="font-size:28px;font-weight:bold;color:${equityColor};margin-top:8px;">${this.fmt(data.equity)}</div>
      </div>
      <div style="margin-top:16px;font-size:11px;color:#64748b;text-align:center;">
        Prepared by CDY Finance System
      </div>
      ${this.footer()}
    </body></html>`;

    this.logger.debug('Generated balance sheet PDF');
    return this.renderPdf(html);
  }
}
