-- Soft-delete columns + indexes (idempotent for re-runs / partial failures)

ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "BankStatement" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "BrandingProject" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "BrandingScopeItem" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "BrandingSupplier" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "BudgetIncreaseRequest" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Bug" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "CampaignInfluencer" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "CommissionRecord" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "CommissionRule" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "DailyActivityLog" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Deliverable" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "DeliverableApproval" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Department" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "DesignSubmission" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "DevSprint" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Influencer" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "InfluencerCampaign" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "LeadActivity" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "LeaveRequest" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "LeaveType" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "MaintenanceLog" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "MarketingClient" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Milestone" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "OnboardingChecklist" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PaymentPlan" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PaymentPlanItem" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PayrollRun" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PerformanceReview" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ProjectBudget" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ProjectFile" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ProjectMember" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ProjectReport" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Proposal" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "RequirementDoc" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "RetainerContract" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "SalesAgent" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "SalesCampaign" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "SalesTarget" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "SavedFilter" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "SoftwareProject" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "SprintItem" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "TaxPayment" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "TaxRate" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Venture" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "WeeklyReport" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "AttendanceRecord_deletedAt_idx" ON "AttendanceRecord"("deletedAt");
CREATE INDEX IF NOT EXISTS "BalanceSheetEntry_deletedAt_idx" ON "BalanceSheetEntry"("deletedAt");
CREATE INDEX IF NOT EXISTS "BankStatement_deletedAt_idx" ON "BankStatement"("deletedAt");
CREATE INDEX IF NOT EXISTS "Bill_deletedAt_idx" ON "Bill"("deletedAt");
CREATE INDEX IF NOT EXISTS "BrandingProject_deletedAt_idx" ON "BrandingProject"("deletedAt");
CREATE INDEX IF NOT EXISTS "BrandingScopeItem_deletedAt_idx" ON "BrandingScopeItem"("deletedAt");
CREATE INDEX IF NOT EXISTS "BrandingSupplier_deletedAt_idx" ON "BrandingSupplier"("deletedAt");
CREATE INDEX IF NOT EXISTS "BudgetIncreaseRequest_deletedAt_idx" ON "BudgetIncreaseRequest"("deletedAt");
CREATE INDEX IF NOT EXISTS "Bug_deletedAt_idx" ON "Bug"("deletedAt");
CREATE INDEX IF NOT EXISTS "CampaignInfluencer_deletedAt_idx" ON "CampaignInfluencer"("deletedAt");
CREATE INDEX IF NOT EXISTS "CashFlowAdjustment_deletedAt_idx" ON "CashFlowAdjustment"("deletedAt");
CREATE INDEX IF NOT EXISTS "Client_deletedAt_idx" ON "Client"("deletedAt");
CREATE INDEX IF NOT EXISTS "CommissionRecord_deletedAt_idx" ON "CommissionRecord"("deletedAt");
CREATE INDEX IF NOT EXISTS "CommissionRule_deletedAt_idx" ON "CommissionRule"("deletedAt");
CREATE INDEX IF NOT EXISTS "ContentItem_deletedAt_idx" ON "ContentItem"("deletedAt");
CREATE INDEX IF NOT EXISTS "CreditNote_deletedAt_idx" ON "CreditNote"("deletedAt");
CREATE INDEX IF NOT EXISTS "DailyActivityLog_deletedAt_idx" ON "DailyActivityLog"("deletedAt");
CREATE INDEX IF NOT EXISTS "Deliverable_deletedAt_idx" ON "Deliverable"("deletedAt");
CREATE INDEX IF NOT EXISTS "DeliverableApproval_deletedAt_idx" ON "DeliverableApproval"("deletedAt");
CREATE INDEX IF NOT EXISTS "Department_deletedAt_idx" ON "Department"("deletedAt");
CREATE INDEX IF NOT EXISTS "DesignSubmission_deletedAt_idx" ON "DesignSubmission"("deletedAt");
CREATE INDEX IF NOT EXISTS "DevSprint_deletedAt_idx" ON "DevSprint"("deletedAt");
CREATE INDEX IF NOT EXISTS "DirectIncome_deletedAt_idx" ON "DirectIncome"("deletedAt");
CREATE INDEX IF NOT EXISTS "Employee_deletedAt_idx" ON "Employee"("deletedAt");
CREATE INDEX IF NOT EXISTS "Expense_deletedAt_idx" ON "Expense"("deletedAt");
CREATE INDEX IF NOT EXISTS "Influencer_deletedAt_idx" ON "Influencer"("deletedAt");
CREATE INDEX IF NOT EXISTS "InfluencerCampaign_deletedAt_idx" ON "InfluencerCampaign"("deletedAt");
CREATE INDEX IF NOT EXISTS "Invoice_deletedAt_idx" ON "Invoice"("deletedAt");
CREATE INDEX IF NOT EXISTS "Lead_deletedAt_idx" ON "Lead"("deletedAt");
CREATE INDEX IF NOT EXISTS "LeadActivity_deletedAt_idx" ON "LeadActivity"("deletedAt");
CREATE INDEX IF NOT EXISTS "LeaveRequest_deletedAt_idx" ON "LeaveRequest"("deletedAt");
CREATE INDEX IF NOT EXISTS "LeaveType_deletedAt_idx" ON "LeaveType"("deletedAt");
CREATE INDEX IF NOT EXISTS "MaintenanceLog_deletedAt_idx" ON "MaintenanceLog"("deletedAt");
CREATE INDEX IF NOT EXISTS "MarketingClient_deletedAt_idx" ON "MarketingClient"("deletedAt");
CREATE INDEX IF NOT EXISTS "Milestone_deletedAt_idx" ON "Milestone"("deletedAt");
CREATE INDEX IF NOT EXISTS "Notification_deletedAt_idx" ON "Notification"("deletedAt");
CREATE INDEX IF NOT EXISTS "OnboardingChecklist_deletedAt_idx" ON "OnboardingChecklist"("deletedAt");
CREATE INDEX IF NOT EXISTS "Payment_deletedAt_idx" ON "Payment"("deletedAt");
CREATE INDEX IF NOT EXISTS "PaymentPlan_deletedAt_idx" ON "PaymentPlan"("deletedAt");
CREATE INDEX IF NOT EXISTS "PaymentPlanItem_deletedAt_idx" ON "PaymentPlanItem"("deletedAt");
CREATE INDEX IF NOT EXISTS "PayrollRun_deletedAt_idx" ON "PayrollRun"("deletedAt");
CREATE INDEX IF NOT EXISTS "PerformanceReview_deletedAt_idx" ON "PerformanceReview"("deletedAt");
CREATE INDEX IF NOT EXISTS "Project_deletedAt_idx" ON "Project"("deletedAt");
CREATE INDEX IF NOT EXISTS "ProjectBudget_deletedAt_idx" ON "ProjectBudget"("deletedAt");
CREATE INDEX IF NOT EXISTS "ProjectFile_deletedAt_idx" ON "ProjectFile"("deletedAt");
CREATE INDEX IF NOT EXISTS "ProjectMember_deletedAt_idx" ON "ProjectMember"("deletedAt");
CREATE INDEX IF NOT EXISTS "ProjectReport_deletedAt_idx" ON "ProjectReport"("deletedAt");
CREATE INDEX IF NOT EXISTS "Proposal_deletedAt_idx" ON "Proposal"("deletedAt");
CREATE INDEX IF NOT EXISTS "RequirementDoc_deletedAt_idx" ON "RequirementDoc"("deletedAt");
CREATE INDEX IF NOT EXISTS "RetainerContract_deletedAt_idx" ON "RetainerContract"("deletedAt");
CREATE INDEX IF NOT EXISTS "SalesAgent_deletedAt_idx" ON "SalesAgent"("deletedAt");
CREATE INDEX IF NOT EXISTS "SalesCampaign_deletedAt_idx" ON "SalesCampaign"("deletedAt");
CREATE INDEX IF NOT EXISTS "SalesTarget_deletedAt_idx" ON "SalesTarget"("deletedAt");
CREATE INDEX IF NOT EXISTS "SavedFilter_deletedAt_idx" ON "SavedFilter"("deletedAt");
CREATE INDEX IF NOT EXISTS "SoftwareProject_deletedAt_idx" ON "SoftwareProject"("deletedAt");
CREATE INDEX IF NOT EXISTS "SprintItem_deletedAt_idx" ON "SprintItem"("deletedAt");
CREATE INDEX IF NOT EXISTS "Task_deletedAt_idx" ON "Task"("deletedAt");
CREATE INDEX IF NOT EXISTS "TaskComment_deletedAt_idx" ON "TaskComment"("deletedAt");
CREATE INDEX IF NOT EXISTS "TaxPayment_deletedAt_idx" ON "TaxPayment"("deletedAt");
CREATE INDEX IF NOT EXISTS "TaxRate_deletedAt_idx" ON "TaxRate"("deletedAt");
CREATE INDEX IF NOT EXISTS "User_deletedAt_idx" ON "User"("deletedAt");
CREATE INDEX IF NOT EXISTS "Venture_deletedAt_idx" ON "Venture"("deletedAt");
CREATE INDEX IF NOT EXISTS "VentureExpense_deletedAt_idx" ON "VentureExpense"("deletedAt");
CREATE INDEX IF NOT EXISTS "VentureIncome_deletedAt_idx" ON "VentureIncome"("deletedAt");
CREATE INDEX IF NOT EXISTS "WeeklyReport_deletedAt_idx" ON "WeeklyReport"("deletedAt");
CREATE INDEX IF NOT EXISTS "roles_deletedAt_idx" ON "roles"("deletedAt");
